### ISSUE TITLE
Kore Converter refactoring according to the new architecture

### ISSUE THREAD

**Issue by fiedlr** [runtimeverification/proof-checker#382]
The overall proposal #373

Current subtasks:

- [x] New abstraction layer (PR 379)
- [x] New tests for the new abstraction layer
- [x] Return functional axioms back (Issue #386)
- [x] Implement the part related to proof generation as proposed in #408
- [x] Update the use of notations and chained applications as soon as notations will be updated, Fix the pretty-printed proofs, Add tests for semantics.notation method, Feed all notations to the ProofExpr #432
- [x] Unit testing as proposed in #418 
- [x] #434

**Comment by fiedlr** [comment]
Closing this as functional axioms are handled by #532 , which is subsumed by #462
