### ISSUE TITLE
Refactor `rewrite_steps.py`

### ISSUE THREAD

**Issue by fiedlr** [runtimeverification/proof-checker#645]
# Intro

Right now, this file is preparing `RewriteStepExpression(pre_config, post_config, axiom, substitutions)` that are fed into the proof generator by zipping through the hint stream.

As `post_config` is never used, and we will have to remove zipping because of simplification events, make the following changes.

# Tasks

- [ ] Remove `conf_after` in `RewriteStepExpression` and all the associated methods. (This will actually be the next `conf_before` for the next rewrite, so this information is duplicate.)
- [ ] Remove the zipping from `get_proof_hints`, this is only used for `post_config` which is removed in step 1. Convert it into a normal forloop that goes through hint after another.
- [ ] Edit all the associated code and tests so that CI passes.
