### ISSUE TITLE
Add simplification events to `rewrite_steps.py` and `execution_proof_generation.py`

### ISSUE THREAD

**Issue by fiedlr** [runtimeverification/proof-checker#646]
# Intro
Simplification events are parsed in the hint files, but currently not processed further

Depends on #645 

# Tasks
- [ ] Update `rewrite_steps.py` to recognize simplification events and yield pre-processed hints for them called `SimplificationStepExpression`. The processed hints should include all the arguments of `simplification_event` with the same types
- [ ] Add tests that a) pre-processed hints are correct 
- [ ] Add unit tests with hardwired hints similar to `test_double_rewrite_semantics`
